### ISSUE TITLE
Object Detection with Yolov8 + Tracking with DeepSORT Code

### ISSUE THREAD

**Issue by Serurays** [insightfulaistrategiesofficial/Object-Detection-and-Tracking#1]
I would like to add the file that has the code for detecting a single person using Yolov8 and also tracking and counting the number of different people using DeepSORT to this repository.

**Comment by UTSAVS26** [comment]
Hi @Serurays, please follow these steps to open a new Issue to make it well structured

### Steps to Open a New Issue

1. **Navigate to Issues**
   - Go to the Issues section of the repository.

2. **Create a New Issue**
   - Click on "New Issue."
   - Select "Feature Request" as the issue type.

3. **Fill Out the Feature Request Form**
   - **Is your feature request related to a problem? Please describe.**
     - Provide a clear and concise description of the problem. For example: "I'm always frustrated when [describe the problem]."
   
   - **Describe the solution you'd like**
     - Outline a clear and concise description of the desired solution or what you want to happen.
   
   - **Describe alternatives you've considered**
     - Describe any alternative solutions or features you've considered.

   - **Additional context**
     - Add any additional context, relevant information, or screenshots related to the feature request.
